---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(crosstalk)
library(d3scatter)
library(plotly)
source('global.R')
# bring in 2018 IR ProbMon CDF results
prob <- read_csv('data/allCDF.csv') %>%
  filter(!is.na(Subpopulation), !is.na(Indicator))


basinSelection <- c("Roanoke Basin", "James Basin", "Potomac-Shenandoah", "Rappahannock-York", "New", "Chowan",
                    "Tennessee", "Holston", "Big Sandy", "Clinch-Powell", "Potomac", "Shenandoah",
                    "Rappahannock", "York")

# Limit to just VSCI data
VSCI <- filter(prob, Indicator == 'VSCIVCPMI') %>%
  filter(Subpopulation %in% basinSelection)
  
  
#shared data for html widgets
shared_VSCI <- SharedData$new(VSCI)
```


### VSCI by Basin
    
    
```{r reg plot}

roanoke <- filter(VSCI, Subpopulation == 'Roanoke Basin') %>%
    select(Value,Estimate.P,LCB95Pct.P,UCB95Pct.P,NResp) %>% as.data.frame()
james <- filter(VSCI, Subpopulation == 'James Basin') %>%
    select(Value,Estimate.P,LCB95Pct.P,UCB95Pct.P,NResp) %>% as.data.frame()


basinVSCI <- data.frame(basin = c('Roanoke Basin', 'James Basin'),
                        VSCIpct = c(vlookup(60,roanoke,2,TRUE),
                                 vlookup(60,james,2,TRUE)))
basinVSCI <- data.frame(basin = c('Roanoke Basin', 'James Basin'),
                        VSCIpct = c(vlookup(100,roanoke,2,TRUE),
                                 vlookup(100,james,2,TRUE)))

p <- ggplot(basinVSCI,aes(basin,VSCIpct))+
  geom_bar(stat='identity', fill="steelblue")+
  labs(title="Percentile by Basins, VSCI = 60", 
       x="Basin", y = "Percentile")

ggplotly(p)
```
    
    
So maybe make a function that takes in an indicator (VSCI), a subpopulation list (basins), and an indicator threshold and split out a dataframe with those percentiles and error bars, then i can use that dataset for my shared dataset for html selection and plotting.
    
    
```{r statewide}
filter_slider("threshold", "Choose an VSCI threshold", shared_VSCI, ~Value)
filter_checkbox('subpopVSCI', 'Choose subpopulations to plot', shared_VSCI, ~Subpopulation, inline = TRUE)
#d3scatter(shared_VSCI, ~Value, ~Estimate.P, ~Indicator)


```



