---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
source('global.R')
# bring in 2018 IR ProbMon CDF results
prob <- read_csv('data/allCDF.csv') %>%
  filter(!is.na(Subpopulation), !is.na(Indicator))
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("subpop", label = "Choose a Subpopulation",
            choices = unique(prob$Subpopulation))

selectInput("indicator", label = "Choose an Indicator",
            choices = unique(prob$Indicator))

checkboxInput('conf',"Plot Confidence Intervals")
```

Column
-----------------------------------------------------------------------


### Geyser Eruption Duration

```{r}
renderPlot({
  dfToPlot <- filter(prob, Subpopulation == input$subpop, Indicator == input$indicator)
 cdfplotFunction(dfToPlot,input$subpop,input$indicator, input$conf)
})
```


